### ISSUE TITLE
Failed to handle method call: Attempt to invoke virtual method 'void android.app.Activity.enterPictureInPictureMode()' on a null object reference

### ISSUE THREAD

**Issue by someq** [bostrot/flutter_android_pip#8]
I am using flutter_android_pip in my Flutter app to enter PiP mode instead of minimizing the app (when user presses home).
It worked fine with code like this:
```
class _MyWidgetState extends State<MyWidget> with WidgetsBindingObserver {
  ...
  void didChangeAppLifecycleState(AppLifecycleState state) {
     if (state == AppLifecycleState.inactive) {
       _enterPipMode();
     }
     else if (state == AppLifecycleState.resumed) {
       _exitPipMode();
     }
  }
  ...
}
```

After I have installed Firebase it stopped working with following error:
```
Failed to handle method call
java.lang.NullPointerException: Attempt to invoke virtual method 'void android.app.Activity.enterPictureInPictureMode()' on a null object reference
	at com.bostrot.flutterandroidpip.FlutterAndroidPipPlugin.onMethodCall(FlutterAndroidPipPlugin.java:26)
	at io.flutter.plugin.common.MethodChannel$IncomingMethodCallHandler.onMessage(MethodChannel.java:233)
	at io.flutter.embedding.engine.dart.DartMessenger.handleMessageFromDart(DartMessenger.java:85)
	at io.flutter.embedding.engine.FlutterJNI.handlePlatformMessage(FlutterJNI.java:692)
	at android.os.MessageQueue.nativePollOnce(Native Method)
	at android.os.MessageQueue.next(MessageQueue.java:325)
	at android.os.Looper.loop(Looper.java:142)
	at android.app.ActivityThread.main(ActivityThread.java:6494)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:438)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:807)
```

Note, it still works if Firebase is not initialized in the code.

Also noted deprecation warning on both plugins:
```
Note: /.../firebase_core-0.7.0/android/src/main/java/io/flutter/plugins/firebase/core/FlutterFirebaseCorePlugin.java uses or overrides a deprecated API.
Note: Recompile with -Xlint:deprecation for details.
Note: /.../firebase_messaging-8.0.0-dev.15/android/src/main/java/io/flutter/plugins/firebase/messaging/FlutterFirebaseMessagingPlugin.java uses or overrides a deprecated API.
Note: Recompile with -Xlint:deprecation for details.
Note: /.../flutter_android_pip-0.0.2/android/src/main/java/com/bostrot/flutterandroidpip/FlutterAndroidPipPlugin.java uses or overrides a deprecated API.
Note: Recompile with -Xlint:deprecation for details.
```

Are these plugins incompatible in some way?

**Comment by someq** [comment]
After digging some code found that [PluginRegistry.Registrar](https://api.flutter.dev/javadoc/io/flutter/plugin/common/PluginRegistry.Registrar.html) which is used to register flutter_android_pip is deprecated (which causes deprecation warning).

Its method [activity](https://api.flutter.dev/javadoc/io/flutter/plugin/common/PluginRegistry.Registrar.html#activity--) may return null, if application has no foreground activity (e.g., when it's paused).

Now seems it's an issue with async receiving of native state events in flutter. As I am trying to enter pip mode when app is minified (home button pressed, etc.) it should be called in `onPause()` callback. But Flutter version of it is called too late to handle the pause. The app is paused, acitivity is no longer visible, thus the error.

It's similar to [this case](https://stackoverflow.com/questions/64286878/flutter-onresume-is-detected-too-late-for-music-pausing). 

Seems Firebase just adds some asynchrounous communication on pause, thats why it does not work with it (firebase takes some time) and works without (firebase does not take any time).

**Comment by bostrot** [comment]
Interesting. I have to read myself into it but it seems [Flutter's Pigeon](https://docs.google.com/document/d/1R-jjZnYUIwpG7Y5EkoHODmlvVeN1zz2Y-lCjTOku9Y0/edit#) is the way to go for synchronous messages.

EDIT: [pre-release here](https://pub.dev/packages/pigeon)

**Comment by someq** [comment]
Indeed Pigeon may work, but right now I made a workaround. It's still asynchronous, but fails less in my case:
* added methods to MainActivity to detect if current screen may enter pip-mode when app is minimized:
```kotlin
class MainActivity: FlutterActivity() {
    // ...
    private var pipAllowed: Boolean = false
    private var pipWidth: Int = 4
    private var pipHeight: Int = 3

    private fun allowPip(width: Int?, height: Int?) {
        pipAllowed = true
        if(width != null && height != null) {
            pipWidth = width
            pipHeight = height
        }
    }

    private fun blockPip() {
        pipAllowed = false
    }
    // ...
```
* implemented native `onUserLeaveHint()` to enter pip mode when user presses home button:
```kotlin
    // ...
    override fun onUserLeaveHint() {
        super.onUserLeaveHint()
        if(pipAllowed && android.os.Build.VERSION.SDK_INT >= android.os.Build.VERSION_CODES.O) {
            val pipParamsBuilder = PictureInPictureParams.Builder();
            pipParamsBuilder.setAspectRatio(Rational(pipWidth, pipHeight))
            enterPictureInPictureMode(pipParamsBuilder.build())
        }
    }
    // ...
```
* added native channel:
```kotlin
class MainActivity: FlutterActivity() {
    private val channel = "my_app/pip_channel"
    // ...

    override fun configureFlutterEngine(flutterEngine: FlutterEngine) {
        super.configureFlutterEngine(flutterEngine)

        MethodChannel(flutterEngine.dartExecutor.binaryMessenger, pipChannel).setMethodCallHandler {
            call, result ->
            when (call.method) {
                "allowPip" -> {
                    val width = call.argument<Int?>("width")
                    val height = call.argument<Int?>("height")
                    allowPip(width, height)
                    result.success(null)
                }
                "blockPip" -> {
                    blockPip()
                    result.success(null)
                }
                else -> {
                    result.notImplemented()
                }
            }
        }
    }
    // ...
```

Now i can access it from my video screen in flutter:
* allow pip mode, when initializing:
```dart
class _MyScreenState extends State<MyScreen> with WidgetsBindingObserver {
  // ...
  static const platform = const MethodChannel('PIP_CHANNEL');  // same as in native code

  @override
  void initState() {
    super.initState();
    platform.invokeMethod('allowPip');
    // ...
  }

  // ...
```
* block pip mode when disposing:
```dart
  // ...
  @override
  void dispose() {
    // ...
    platform.invokeMethod('blockPip');
    super.dispose();
  }

  // ...
```
* still need to handle local state to hide unnecessary controls, etc. in pip mode:
```dart
  // ...
  bool _pipMode = false;
  
  void didChangeAppLifecycleState(AppLifecycleState state) {
    // may also check for android sdk level >= 26 here
    if (state == AppLifecycleState.inactive) {
      setState(() { _pipMode = true; });
    }
    else if (state == AppLifecycleState.resumed) {
      setState(() { _pipMode = false; });
    }
  }
  // ...
```

Downsides of this approach are:
* Application may fail to enter pip mode if minimized too fast right after entering pip screen.
* Application may enter pip mode on other screen if minimized too fast after exiting pip screen.
* You have to deal with flutter native channels yourself.
